### ISSUE TITLE
Separate connection pooling from mutex {un,}locking

### ISSUE THREAD

**Issue by dcelasun** [hjr265/redsync.go#10]
The [godoc example](https://godoc.org/github.com/hjr265/redsync.go/redsync#example-Mutex) (and all other New\* functions) require passing Redis credentials/connections everytime when acquiring a mutex.

Instead of that, an API that separates connections from mutexes seems much more usable. For example:

``` go
// redsync.New returns *RedSync
redsync := redsync.New([]net.Addr{
    &net.TCPAddr{Port: 6379},
    &net.TCPAddr{Port: 6380},
})

lock, err := redsync.Lock("foo")
if err != nil {
    // success!
}

redsync.Unlock(lock)
```

This way, a single `RedSync` instance could be shared across the codebase without dealing with connection parameters everywhere. What do you think?

**Comment by csesmita** [comment]
My 2 cents:

I think that is a doable idea, but depends on how backward compatible it is with existing applications. Changing the API signature might not be a good idea, however, new APIs that return just a connection pool might be the way forward. 
Therefore, I would think potentially we are looking at something like this:

// redsync.New returns *RedSync
redsync := redsync.New([]net.Addr{
    &net.TCPAddr{Port: 6379},
    &net.TCPAddr{Port: 6380},
})

// Initialise the mutex with a new APi in order to keep Lock API the same
m, err := redsync.NewMutexWithInitPool(name string)
...// err handling

err := m.Lock()
if err != nil {
    // success!
}

m.Unlock()

**Comment by dcelasun** [comment]
Yeah, that would probably be best for BC purposes. @hjr265 what do you think? Are you open to a new API like this?

If not, I'll probably write my own library for it, so there won't be any BC concerns.

**Comment by dcelasun** [comment]
@hjr265 any updates on this? Would you be willing to merge a PR?

**Comment by hjr265** [comment]
Hi @dcelasun.. Thank you for sharing this suggestion.. I like the idea! And, yes.. It would definitely be nice to have this done without breaking backward compatibility.. (Thanks @csesmita for pointing that out)..

A pull request would be really great!

**Comment by dcelasun** [comment]
Great! I'll probably send the PR over the weekend.

**Comment by hjr265** [comment]
@dcelasun Thank you!
